# Build Sanity/Smoke Test for go-mosh
#
# Note: This just verifies that mosh can be compiled, that `go build` works, and that the mosh version can be read at
# runtime via a trivial unit test.

image: "ubuntu:jammy"

stages:
  - build

before_script:
  - apt-get update -qq
  # certs and git to pull the mosh submodule; swig and golang to build go-mosh
  - apt-get install -y -qq ca-certificates git swig golang-1.18
  # packages required to build mosh
  - apt-get install -y -qq autoconf make pkg-config libncurses-dev protobuf-compiler libprotobuf-dev zlib1g-dev libssl-dev
  # use clang instead of g++/gcc to build mosh and the cgo dependency in go-mosh
  - apt-get install -y -qq clang

sanity_check:
  stage: build
  script:
    - git submodule update --init
    # note: using explicit CC/CXX settings to clang as setting the system compiler was not sufficient for invoking go
    - CC="clang" CXX="clang++" ./build-mosh.sh
    - CC="clang" CXX="clang++" /usr/lib/go-1.18/bin/go build ./...
    - CC="clang" CXX="clang++" /usr/lib/go-1.18/bin/go test ./test/mosh
